import './globals.css'
import { ClerkProvider } from '@clerk/nextjs/app-beta'
import { Toaster } from 'react-hot-toast'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className="h-screen w-screen bg-bg-dark text-body-text-light">
                    {children}
                    <Toaster position="top-right" />
                </body>
            </html>
        </ClerkProvider>
    )
}
